### PR TITLE
#115 [`SPANS`] Made `underlineOffset` compatible with the `box-sizing: border-box`

### PR DESCRIPTION
**Pull request by oleksandr-danylchenko**
## Issue
See - https://github.com/recogito/text-annotator-js/issues/115

## Changes Made
1. ~Replaced offset definition using the `paddingBottom` with the `height`. In that way, the height of the highlight span will get properly extended both using the `content-box` and `border-box`.~, see https://github.com/recogito/text-annotator-js/pull/116#issuecomment-2213215373
2. Added `box-sizing: border-box` reset to the `test` examples

## Disclaimer
Most of the changes come from the IDE's formatted that applied 2 space indentation to the `test` files. To see only meaningful differences - hide the whitespace diff:

### CODE REVIEW

**Comment by rsimon** [comment]
I might be missing something here. But isn't that just a different way to achieve the same result? Either you apply height + padding, or use `box-sizing: border-box` and change the height. If we want to protect against an external stylesheet unintentionally setting `border-box` on the highlight layer element, we should probably just give it `box-sizing: content-box` explicitely?

**Comment by oleksandr-danylchenko** [comment]
> I might be missing something here. But isn't that just a different way to achieve the same result?

Yeah, it is. The `box-sizing: border-box` is just a more widespread and intuitive sizing approach.

> on the highlight layer element, we should probably just give it box-sizing: content-box explicitly?

However, I think that this suggestion makes sense, and applying `box-sizing: content-box` to the `.r6o-annotation` will our needs

**Comment by rsimon** [comment]
I think this can be closed in favor of https://github.com/recogito/text-annotator-js/commit/dbdbf86b3d09e8db17ce7e21ceed6477e953078f?

**Comment by oleksandr-danylchenko** [comment]
I think this PR can still be beneficial for:
- Traceability of the changes. It explicitly describes that we intend to support the `content-box`
- Makes the `border-box` a default for the test pages, which is relevant for the prevailing majority of the consumers
- Applied the IDE's autoformatting and frees me from constantly tweaking it 😅

**Pull request merged**
