### PR TITLE
#71 Fixed losing the `styleClass` on `W3CTextAnnotation` parsing

### PR DESCRIPTION
**Pull request by oleksandr-danylchenko**
## Issue
This PR resolves the #71 issue. Left there a detailed explanation behind the change

## Changes Made
1. Added copying of the `styleClass` from the `W3CTextAnnotation` to the `TextAnnotation`
3. Added error reporting when there are no targets on the annotation

### CODE REVIEW

**Comment by oleksandr-danylchenko** [comment]
Could this PR be merged to reduce the number of opened ones? 🙏🏻

**Comment by oleksandr-danylchenko** [comment]
Merge candidate? Seems like a pretty small, but beneficial, change 🤔

**Comment by oleksandr-danylchenko** [comment]
@rsimon, I reworked the PR according to the approach you took for the `scope` property in https://github.com/recogito/text-annotator-js/commit/068e537c97b563c7af25f6141a13b8433d77cbdd.
Now the `styleClass` is "silently" serialized/deserialized in the core model and I used milder `@ts-expect-error` instead of `@ts-ignore`.

**Comment by rsimon** [comment]
Great, thanks!

**Pull request merged**
